name: Execute

on:
  workflow_dispatch:
  schedule:    
    - cron: "*/20 * * * *"
  
jobs:
  execute:
    runs-on: ubuntu-latest
    
    env:
      TODOIST_API_TOKEN: ${{ secrets.TODOIST_API_TOKEN }}
      HABITICA_USER_ID: ${{ secrets.HABITICA_USER_ID }}
      HABITICA_API_KEY: ${{ secrets.HABITICA_API_KEY }}
    
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '18'
          
      - run: yarn install
      - run: yarn run execute
